apiVersion: v1
kind: Template
labels:
  template: generalised-pipeline
metadata:
  name: generalised-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${TARGET_APP}
    name: ${TARGET_APP}-pipeline
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${TARGET_APP}", "namespace": "${DEV_PROJECT}", "kind": "BuildConfig"},{"name": "${TARGET_APP}", "namespace": "${TEST_PROJECT}", "kind": "DeploymentConfig"},{"name": "${TARGET_APP}-green", "namespace": "${PROD_PROJECT}", "kind": "DeploymentConfig"},{"name": "${TARGET_APP}-blue", "namespace": "${PROD_PROJECT}", "kind": "DeploymentConfig"}]'
  spec:
    runPolicy: Serial
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          node ('maven') {
            stage 'Build'
            openshiftBuild(buildConfig: '${TARGET_APP}', namespace: '${DEV_PROJECT}', showBuildLogs: 'true')

            stage 'Run Tests in DEV'
            sleep 10

            stage 'Deploy to UAT'
            openshiftTag(sourceStream: '${TARGET_APP}', sourceTag: 'latest', namespace: '${DEV_PROJECT}', destinationStream: '${TARGET_APP}', destinationTag: 'uat', destinationNamespace: '${TEST_PROJECT}')
            sleep 10

            stage 'Run Tests in TEST'
            sleep 30
          }

          def tag="blue"
          def altTag="green"

          node {
            stage 'Deploy to PROD (Not Live)'
            sh "oc get route ${TARGET_APP} -n ${PROD_PROJECT} -o jsonpath='{ .spec.to.name }' > activeservice"
            activeService = readFile('activeservice').trim()
            if (activeService == "${TARGET_APP}-blue") {
              tag = "green"
              altTag = "blue"
            }
            openshiftTag(sourceStream: '${TARGET_APP}', sourceTag: 'uat', namespace: '${TEST_PROJECT}', destinationStream: '${TARGET_APP}', destinationTag: "prod-${tag}", destinationNamespace: '${PROD_PROJECT}')
            sleep 10
            openshiftVerifyDeployment(deploymentConfig: "${TARGET_APP}-${tag}", replicaCount: 1, verifyReplicaCount: true, namespace: '${PROD_PROJECT}')

            stage 'Smoke Tests in PROD (Not Live)'
            sleep 30
          }

          stage 'Approve Go Live'
          timeout(time:30, unit:'MINUTES') {
            input message:'Go Live in Production (switch to new version)?'
          }

          node {
            stage 'Go Live'
            sh "oc set route-backends ${TARGET_APP} ${TARGET_APP}-${tag}=100 ${TARGET_APP}-${altTag}=0 -n ${PROD_PROJECT}"
            sh "oc label svc ${TARGET_APP}-${altTag} app=${TARGET_APP}-idle --overwrite -n ${PROD_PROJECT}"
            sh "oc label svc ${TARGET_APP}-${tag} app=${TARGET_APP}-live --overwrite -n ${PROD_PROJECT}"
            sleep 5
          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
parameters:
- description: The name for the pipeline.
  displayName: Pipeline Name
  name: TARGET_APP
  required: true
- description: DEV project name containing the buildconfigs
  displayName: DEV Project Name
  name: DEV_PROJECT
  required: true
- description: TEST project name containing the buildconfigs
  displayName: TEST Project Name
  name: TEST_PROJECT
  required: true
- description: PROD project name containing the buildconfigs
  displayName: PROD Project Name
  name: PROD_PROJECT
  required: true

